# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeve < Formula
  desc ""
  homepage "https://github.com/a0xAi/kubeve"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.4.0/kubeve_Darwin_x86_64.tar.gz"
      sha256 "4428204c6770ce2a858835840aaa9f976e2212058b03b569462fd7390faead43"

      def install
        bin.install "kubeve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.4.0/kubeve_Darwin_arm64.tar.gz"
      sha256 "e8b9f7a8391ed530603797156a04b0ba1a221f7478487d7b1d2a077ae260ae7c"

      def install
        bin.install "kubeve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.4.0/kubeve_Linux_x86_64.tar.gz"
      sha256 "4337455a040badbb082e9379a991871989b9fcf7223465886367da28b1b11fbe"
      def install
        bin.install "kubeve"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.4.0/kubeve_Linux_arm64.tar.gz"
      sha256 "6126a2ce4df2356505b166deb0734deef2126f27930aec015c9dadeb021dd8aa"
      def install
        bin.install "kubeve"
      end
    end
  end
end
